### ISSUE TITLE
Where can I find the config files for the Daemons I create?

### ISSUE THREAD

**Issue by leothelocust** [mulian/smart-daemon-control#5]
Great tool so far, but I'm hoping to discover a way to do something like this:

stop command: `/usr/local/bin/pm2 kill && launchctl unload /Users/lolson/.mycustomdaemons/pm2.plist`

I am hoping this solves my issue of `launchctl unload` not actualling killing the pm2 app.

**Comment by mulian** [comment]
Sorry, i'm just very busy.

There is no config File. The data is stored directly in Atom (state).

Currently you could only run one command. 
Smart-Daemon-Control separates the first string (separation by blank) in a command and all other (following) strings into input parameters for Atom's [BufferedProcess](https://atom.io/docs/api/v1.4.3/BufferedProcess). 
Therefore, the input _'&& launchctl unload'_ is treated like a input parameter.

But you can just use a bash script?

**Comment by leothelocust** [comment]
Thanks for the info! Yeah, I totally didn't even think of using a bash script, good idea.

Thanks again!

**Comment by leothelocust** [comment]
In case it may be helpful to another who stumbles across this, below is the simple bash file I created.

``` bash
#!bin/bash

launchctl unload /Users/lolson/.mycustomdaemons/pm2.plist
pm2 kill
```

My stop command just calls that above script.  I had to `chmod u+x my_stop_script.sh`, but then it worked.

Hope someone else finds this helpful
